/*
================================
| USE "DATATABSE" |
================================
*/

Use OnlineRetail;

/*
================================
| Create Optimized "Fact Table" |
================================
*/
SELECT 
	Invoice,
	InvoiceDate,
	CustomerID =[Customer ID],
	StockCode,
	Quantity,
	Revenue
INTO fact_sales
FROM fact_sales_raw;
GO

/*
=====================================
| Create "Customer Dimension Table" |
=====================================
*/

--- Remove the table,if it already exists to avoid errors
DROP TABLE IF EXISTS dim_customer;

--- Create structure 
CREATE TABLE dbo.dim_customer (
    CustomerID INT NOT NULL,
    Country    VARCHAR(50) NOT NULL,
    CONSTRAINT PK_dim_customer PRIMARY KEY (CustomerID)
);
GO

--- Insert data
INSERT INTO dim_customer (CustomerID, Country)
SELECT
    CustomerID,
    Country
FROM (
    SELECT
        CAST([Customer ID] AS INT) AS CustomerID,
        Country,
        ROW_NUMBER() OVER (
            PARTITION BY CAST([Customer ID] AS INT) -- Groups rows by customer
            ORDER BY InvoiceDate DESC
        ) AS rn
    FROM dbo.fact_sales_raw
) t
WHERE rn = 1; 
---One row per customer Guaranteed no duplicates
GO

/*
====================================
| Create "Product Dimension Table" |
====================================
*/
SELECT DISTINCT
	StockCode,
	Description
INTO dim_product
FROM fact_sales_raw;
GO

/*
============================================
| ⏱️ Validation Checks: COUNT SANITY CHECK|
===========================================
*/

---Row count consistency - HENCE must match
SELECT 
	COUNT(*) AS SALES_ROWS
FROM fact_sales;
GO

SELECT 
	COUNT(*) SALES_ROWS_RAW
FROM fact_sales_raw;
GO

--- Customer count sanity
SELECT 
	COUNT(DISTINCT CustomerID) 
FROM fact_sales; -- from fact table
GO

SELECT 
	COUNT(*) 
FROM dim_customer; -- from dimension table
GO


/*
=======================================
| Create Indexes - FACT TABLE INDEXES |
=======================================
*/

----- Customer-centric analytics (RFM)
CREATE CLUSTERED INDEX idx_fact_customer
ON fact_sales (CustomerID);
GO

-- Time-based analytics (recency, cohorts)
CREATE NONCLUSTERED INDEX idx_fact_date
ON fact_sales (InvoiceDate);
GO

-- Frequency accuracy
CREATE NONCLUSTERED INDEX idx_fact_invoice
ON fact_sales (Invoice); -- error
GO

/*
===========================
| BUILD Customer 360 View |
===========================
*/
CREATE VIEW vw_customer_360
AS
SELECT 
	c.CustomerID,
	c.Country
FROM fact_sales f
JOIN dim_customer c
	ON f.CustomerID = c.CustomerID
GROUP BY 
	c.CustomerID,
	c.Country;
GO

--- Alter the View
CREATE OR ALTER VIEW dbo.vw_customer_360
AS
SELECT
    c.CustomerID,
    c.Country,

    -- Frequency: number of unique purchase events, and Prevents over-counting multi-item invoices
    COUNT(DISTINCT f.Invoice) AS Frequency,

    -- Monetary: total revenue generated by the customer
    SUM(f.Revenue) AS Monetary,

    -- Anchor date for recency calculation
    MAX(f.InvoiceDate) AS LastPurchaseDate
FROM dbo.fact_sales f
INNER JOIN dbo.dim_customer c
    ON f.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.Country;
GO



/*
=============================
| ⏱️ Performance Validation |
=============================
*/
SET STATISTICS TIME ON;
SELECT TOP 100* FROM vw_customer_360;
GO

SET STATISTICS TIME ON;
SELECT COUNT(*) FROM fact_sales;
GO


/*
=============================
| FINAL DATA QUALITY CHECKS |
=============================
*/

---One row per customer
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT CustomerID) AS distinct_customers
FROM dbo.vw_customer_360;

---No zero or/ negative values
SELECT COUNT(*) 
FROM dbo.vw_customer_360
WHERE Frequency <= 0
   OR Monetary <= 0;

 ---No NULL anchor dates
SELECT COUNT(*)
FROM dbo.vw_customer_360
WHERE LastPurchaseDate IS NULL;


/*
==========================================
| VERIFY NEW TABLE:mba_rules FROM Python |
==========================================
*/
SELECT 
    COUNT(*) 
FROM dbo.mba_rules;
GO

SELECT 
    TOP 10 *
FROM dbo.mba_rules
ORDER BY lift DESC;
GO

/*
===================
| clustered index |
===================
*/
CREATE CLUSTERED INDEX IX_mba_rules_lift
ON dbo.mba_rules (lift DESC);

/*
=======================================
| VERIFY NEW cohort_table FROM Python |
=======================================
*/

SELECT TOP 10 *
FROM dbo.cohort_table
ORDER BY CohortMonth, CohortIndex;

