/*
=======================================
| Create Indexes - FACT TABLE INDEXES |
=======================================
*/

----- Customer-centric analytics (RFM)
CREATE CLUSTERED INDEX idx_fact_customer
ON fact_sales (CustomerID);
GO

-- Time-based analytics (recency, cohorts)
CREATE NONCLUSTERED INDEX idx_fact_date
ON fact_sales (InvoiceDate);
GO

-- Frequency accuracy
CREATE NONCLUSTERED INDEX idx_fact_invoice
ON fact_sales (Invoice); -- error
GO

/*
===========================
| BUILD Customer 360 View |
===========================
*/
CREATE VIEW vw_customer_360
AS
SELECT 
	c.CustomerID,
	c.Country
FROM fact_sales f
JOIN dim_customer c
	ON f.CustomerID = c.CustomerID
GROUP BY 
	c.CustomerID,
	c.Country;
GO

--- Alter the View
CREATE OR ALTER VIEW dbo.vw_customer_360
AS
SELECT
    c.CustomerID,
    c.Country,

    -- Frequency: number of unique purchase events, and Prevents over-counting multi-item invoices
    COUNT(DISTINCT f.Invoice) AS Frequency,

    -- Monetary: total revenue generated by the customer
    SUM(f.Revenue) AS Monetary,

    -- Anchor date for recency calculation
    MAX(f.InvoiceDate) AS LastPurchaseDate
FROM dbo.fact_sales f
INNER JOIN dbo.dim_customer c
    ON f.CustomerID = c.CustomerID
GROUP BY
    c.CustomerID,
    c.Country;
GO



/*
=============================
| ⏱️ Performance Validation |
=============================
*/
SET STATISTICS TIME ON;
SELECT TOP 100* FROM vw_customer_360;
GO

SET STATISTICS TIME ON;
SELECT COUNT(*) FROM fact_sales;
GO


/*
=============================
| FINAL DATA QUALITY CHECKS |
=============================
*/

---One row per customer
SELECT
    COUNT(*) AS rows,
    COUNT(DISTINCT CustomerID) AS distinct_customers
FROM dbo.vw_customer_360;

---No zero or/ negative values
SELECT COUNT(*) 
FROM dbo.vw_customer_360
WHERE Frequency <= 0
   OR Monetary <= 0;

 ---No NULL anchor dates
SELECT COUNT(*)
FROM dbo.vw_customer_360
WHERE LastPurchaseDate IS NULL;
